/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbank;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author dell pc
 */
public class Donor1 extends javax.swing.JFrame {

    /**
     * Creates new form Donor1
     */
    public Donor1() {
        initComponents();
        this.getContentPane().setBackground(Color.YELLOW);
    }
    public void selectionall(){try{
              Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Project", "Anmol", "1234");
              Statement st=con.createStatement();
              String bgp;
           bgp =   (String) JBloodGroup.getSelectedItem();
           String a;
           a = (String)JQuantity.getSelectedItem();
           int stock;
           stock = Integer.parseInt(a);
           String sql = "Select STOCK from BLOODBANK where BLoodGROUP = '"+bgp+"'";
           ResultSet rs;
           rs = st.executeQuery(sql);
           String l;
           while(rs.next()){
           int stk=rs.getInt("STOCK");
           stk = stk + stock;
          // String l;
               l = Integer.toString(stk);
       
           
           


           String query="Update BLOODBANK Set STOCK = "+l+" where BLOODGROUP = '"+bgp+"'";
           st.executeUpdate(query);
               break;
           }
           
           
                         
                           
                  // PreparedStatement st= myconObj.createStatement();
                
                   //  st.executeUpdate(sql);
                   //System.out.println("rows affected"+count);
       }
        catch(SQLException e){
           e.printStackTrace();
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TWeight = new javax.swing.JTextField();
        LMWeight = new javax.swing.JLabel();
        LQuantity = new javax.swing.JLabel();
        JQuantity = new javax.swing.JComboBox<>();
        LDiseases = new javax.swing.JLabel();
        RBtnYes = new javax.swing.JRadioButton();
        RBtnNo = new javax.swing.JRadioButton();
        BtnBack = new javax.swing.JButton();
        BtnSubmit = new javax.swing.JButton();
        LBloodGroup = new javax.swing.JLabel();
        JBloodGroup = new javax.swing.JComboBox<>();
        LWeight = new javax.swing.JLabel();
        LMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("DONOR");

        LQuantity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LQuantity.setText("QUANTITY(no.of bottles each of 160ml )");

        JQuantity.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        JQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        LDiseases.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LDiseases.setText("DO YOU HAVE ANY DISEASES");

        RBtnYes.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        RBtnYes.setText("YES");

        RBtnNo.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        RBtnNo.setText("NO");

        BtnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BtnBack.setText("BACK");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnSubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BtnSubmit.setText("SUBMIT");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        LBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LBloodGroup.setText("BLOOD GROUP");

        JBloodGroup.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        JBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        LWeight.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LWeight.setText("WEIGHT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LQuantity)
                            .addComponent(LDiseases, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(RBtnYes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(RBtnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(LWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(BtnBack)
                        .addGap(87, 87, 87)
                        .addComponent(BtnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(LMWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBloodGroup)
                    .addComponent(JBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LMWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDiseases, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBtnYes)
                    .addComponent(RBtnNo))
                .addGap(18, 18, 18)
                .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnBack)
                    .addComponent(BtnSubmit))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        bg.add(RBtnYes);
        bg.add(RBtnNo);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
     new Donor().setVisible(true);
     this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
     int weight=Integer.parseInt(TWeight.getText());
         if(weight<45)
         {
             JOptionPane.showMessageDialog(null,"YOU ARE UNDERWEIGHT,YOU CANNOT DONATE BLOOD","MESSAGE",JOptionPane.INFORMATION_MESSAGE);
            new Hospital().setVisible(true);
             this.setVisible(false);
         }
         
         
         
         
         
        
       else if(RBtnYes.isSelected())
      {
          this.setVisible(false);
          JOptionPane.showMessageDialog(null,"YOU CANNOT DONATE THE BLOOD,SORRRY ","SORRY",JOptionPane.INFORMATION_MESSAGE);
           new Hospital().setVisible(true);
             this.setVisible(false);
      }
      else
      {
          this.setVisible(false);
          selectionall();
          JOptionPane.showMessageDialog(null,"YOU CAN DONATE THE BLOOD AT NEAREST MAHATMA GANDHI BLOOD BANK ","THANKS",JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null,"THANKS FOR DONATING BLOOD,YOUR BLOOD WILL SAVE SOMEONE'S LIFE","THANKS",JOptionPane.INFORMATION_MESSAGE);       
           new Hospital().setVisible(true);
      }
     
// TODO add your handling code here:
    }//GEN-LAST:event_BtnSubmitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Donor1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JComboBox<String> JBloodGroup;
    private javax.swing.JComboBox<String> JQuantity;
    private javax.swing.JLabel LBloodGroup;
    private javax.swing.JLabel LDiseases;
    private javax.swing.JLabel LMWeight;
    private javax.swing.JLabel LMessage;
    private javax.swing.JLabel LQuantity;
    private javax.swing.JLabel LWeight;
    private javax.swing.JRadioButton RBtnNo;
    private javax.swing.JRadioButton RBtnYes;
    private javax.swing.JTextField TWeight;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
